Deactive pypy 531, error need to be fixed:
    cc -O2 -fPIC -Wimplicit -DCYTHON_CLINE_IN_TRACEBACK=1 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/home/travis/virtualenv/pypy-5.3.1/include -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
    src/lxml/etree.c:1294:3: error: unknown type name ‘PyBaseExceptionObject’
       PyBaseExceptionObject __pyx_base;
       ^
    Compile failed: command 'cc' failed with exit status 1
    cc -O2 -fPIC -Wimplicit -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInit5q2Lb3.c -o tmp/xmlXPathInit5q2Lb3.o
    /tmp/xmlXPathInit5q2Lb3.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    cc tmp/xmlXPathInit5q2Lb3.o -lxml2 -o a.out
    error: command 'cc' failed with exit status 1